language: java
jdk:
  - openjdk23

addons:
  sonarcloud:
    organization: "endervasik-mirea"
    token:
      secure: $SONAR_TOKEN

script:
  # Создаем папку для скомпилированных файлов и компилируем код
  - mkdir -p telephone-task/out
  - javac -d telephone-task/out telephone-task/src/Main.java
  # Запускаем анализатор SonarCloud
  - sonar-scanner